[package]
name = "tokio_rcu"
version = "0.1.0"
edition = "2024"

[dependencies]
index_type = "0.7.1"
spin = { version = "0.12.2", features = ["fair_mutex"] }
tokio = { version = "1.53.1", features = ["sync", "rt"] }

[target.'cfg(loom)'.dependencies]
loom = "0.7.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Win32_System_Threading"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(loom)"] }
