name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_ALL_FEATURES_VERSION: "1.12.0"
  CARGO_REEDME_VERSION: "0.6.1"
  OS_OPTIONS: '["ubuntu-latest", "ubuntu-24.04-arm", "windows-latest", "windows-11-arm"]'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        os: ${{ fromJSON(env.SUPPORTED_OS) }}
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: --cfg tokio_unstable -D warnings
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install --locked cargo-all-features@$CARGO_ALL_FEATURES_VERSION
      - run: cargo all-features check --all-targets

  tests-release-mode:
    strategy:
      matrix:
        os: ${{ fromJSON(env.SUPPORTED_OS) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install --locked cargo-all-features@$CARGO_ALL_FEATURES_VERSION
      - run: cargo all-features nextest run --release

  tests-debug-mode:
    strategy:
      matrix:
        os: ${{ fromJSON(env.SUPPORTED_OS) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install --locked cargo-all-features@$CARGO_ALL_FEATURES_VERSION
      - run: cargo all-features nextest run

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo install --locked cargo-all-features@$CARGO_ALL_FEATURES_VERSION
      - run: cargo all-features clippy --all-targets -- -D warnings

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly

      - run: cargo +nightly install --locked cargo-reedme@$CARGO_REEDME_VERSION
      - run: cargo +nightly reedme --check

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: --cfg tokio_unstable -D warnings
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo install --locked cargo-all-features@$CARGO_ALL_FEATURES_VERSION
      - run: cargo all-features doc --no-deps

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: crate-ci/typos@v1.49.0
